name: Automerge

on:
  pull_request:
    branches: [ development ]

jobs:
  automerge:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ success() }}
    steps:
    - name: Merge to development
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "auto-merge"
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "pull-request-description"
        MERGE_RETRIES: "6"
        MERGE_RETRY_SLEEP: "10000"
        UPDATE_METHOD: "rebase"